version: '3.8'

services:
    nginx:
        image: nginx:1.25.2
        container_name: nginx_container
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/ssl:/etc/nginx/ssl
            - ${PWD}:/var/www/html
        depends_on:
            - php
        networks:
            - app-network

    php:
        build: ./docker/php
        image: php_image
        container_name: php_container
        volumes:
            - ${PWD}:/var/www/html
        networks:
            - app-network

    db:
        image: mysql:8.1.0
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
